"""init schema

Revision ID: ff450f3ae804
Revises: 
Create Date: 2025-08-18 17:39:50.852161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff450f3ae804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=True),
    sa.Column('tenant_slug', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_university_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_university_tenant_slug'), ['tenant_slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.String(length=32), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('pro_since', sa.DateTime(), nullable=True),
    sa.Column('pro_cancel_at', sa.DateTime(), nullable=True),
    sa.Column('coins_free', sa.Integer(), nullable=False),
    sa.Column('coins_pro', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_university_id'), ['university_id'], unique=False)

    op.create_table('agent_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_job_user_id'), ['user_id'], unique=False)

    op.create_table('free_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature', 'day', name='uq_free_usage_user_feature_day')
    )
    with op.batch_alter_table('free_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_free_usage_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_usage_feature'), ['feature'], unique=False)
        batch_op.create_index('ix_free_usage_user_feature_day', ['user_id', 'feature', 'day'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_usage_user_id'), ['user_id'], unique=False)

    op.create_table('internship_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internship_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internship_record_user_id'), ['user_id'], unique=False)

    op.create_table('jobpack_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobpack_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobpack_report_user_id'), ['user_id'], unique=False)

    op.create_table('outreach_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_contact_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_page_user_id'), ['user_id'], unique=False)

    op.create_table('resume_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_asset_user_id'), ['user_id'], unique=False)

    op.create_table('skillmap_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_title', sa.String(length=200), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('skills_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skillmap_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skillmap_snapshot_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skillmap_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skillmap_snapshot_user_id'))

    op.drop_table('skillmap_snapshot')
    with op.batch_alter_table('resume_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_asset_user_id'))

    op.drop_table('resume_asset')
    with op.batch_alter_table('portfolio_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_page_user_id'))

    op.drop_table('portfolio_page')
    with op.batch_alter_table('outreach_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_contact_user_id'))

    op.drop_table('outreach_contact')
    with op.batch_alter_table('jobpack_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobpack_report_user_id'))

    op.drop_table('jobpack_report')
    with op.batch_alter_table('internship_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internship_record_user_id'))

    op.drop_table('internship_record')
    with op.batch_alter_table('free_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_usage_user_id'))
        batch_op.drop_index('ix_free_usage_user_feature_day')
        batch_op.drop_index(batch_op.f('ix_free_usage_feature'))
        batch_op.drop_index(batch_op.f('ix_free_usage_day'))

    op.drop_table('free_usage')
    with op.batch_alter_table('agent_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_job_user_id'))

    op.drop_table('agent_job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_university_id'))
        batch_op.drop_index(batch_op.f('ix_user_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_user_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_university_tenant_slug'))
        batch_op.drop_index(batch_op.f('ix_university_domain'))

    op.drop_table('university')
    # ### end Alembic commands ###
